"""
Django settings for hzWebSiteApi project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from hzWebSiteApi import params
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

print("params.DEBUG -->", params.DEBUG)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xz2wx-#(%$344x38@ha6xr)#!o2bhgx5f-#&g9vaecvxw9*g3u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'hurong'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    '*'
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)


ROOT_URLCONF = 'hzWebSiteApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hzWebSiteApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hzWebSiteDB',
        'USER': 'hzWebSiteApi',
        'PASSWORD': 'JzQRcy7D23UN2YddB3N',
        'HOST': 'hzWebSiteDB',
        'PORT': '3306',
        # 'OPTIONS': {
        #     'init_command': 'SET storage_engine=INNODB',
        # },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True

USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# STATIC_URL = '/static/'


STATIC_URL = '/statics/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'statics')]

# 不验证token的请求
NoValidationTokenRoute = [
    "/api/tripartite_platform/authorization",
    "/api/tripartite_platform/get_ticket",
    "/api/tripartite_platform/tongzhi",

    "/api_hurong/task_list/save_task",
    "/api_hurong/xhs_phone_log/add",
    "/api_hurong/task_list/get_task",
    "/api_hurong/task_list/get_xiala_keywords",
    "/api_hurong/xiaohongshufugai/get_task",
    "/api_hurong/xiaohongshufugai/is_selected_rank",
    "/api/wechat/login_qrcode",
    "/api_hurong/xiaohongshu/check_forbidden_text",
    "/api_hurong/xiaohongshu_userprofile/is_update_userinfo",
    "/api_hurong/xiaohongshu_userprofile/update_userinfo",
    "/api_hurong/xiaohongshu_userprofile/registre",
    "/api_hurong/xiaohongshu_biji/add",
    "/api_hurong/xiaohongshu_biji/get_release_task",
    "/api_hurong/xiaohongshu_biji/upload_url",
    "/api_hurong/xiaohongshu_direct_essages/save_screenshots",

    "/api_hurong/xiaohongshu_direct_essages/reply",
    "/api_hurong/xiaohongshu_direct_essages/reply_save",
    "/api_hurong/xiaohongshu_direct_essages/get_reply",
    "/api_hurong/xiaohongshu_direct_essages/get_screenshot_time",
    "/api_hurong/xiaohongshu_direct_essages",
    "/api_hurong/xhs_king_barings_screen/get_xhs_account",
    "/api_hurong/package_management/get_highest_version",
    "/api_hurong/xhs_king_barings_screen/get_coverage_quantity",
    "/api_hurong/comment_management/mobile_phone_reviews",
    "/api_hurong/comment_management/reply_comment",
]
